### ISSUE TITLE
Authorization works, but tries to edit qutepocket wiki

### ISSUE THREAD

**Issue by mediapathic** [kepi/qutepocket#3]
In my config.py I put

```
config.bind(",P", "spawn --userscript qutepocket")
```

I run `,P`. I get the Pocket authorization page, and it works as expected. But when I click through there, I am redirected to [the qutepocket wiki](https://github.com/kepi/qutepocket/wiki) with, quite reasonably, the error that I am not allowed to edit it.

This is probably a minor issue, as the authorization seems to have worked, and multiple Pocket saves after this are working fine. But I figured you should know about it. 

(MacOS, qutebrowser v1.14.1)

**Comment by kepi** [comment]
Thanks, I see what happened. I was too creative with wiki article title :) and didn't know that changing title also changes URL.

Should be fixed now. Thanks for letting me know!
